"""
E-Commerce Customer Analysis
Author: Aditya Dubey

Goal:
To understand how customers behave on the platform,
what is driving revenue, where we are losing customers,
and what actions the business can take to improve performance.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Set visualization style
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

print("="*80)
print("E-COMMERCE CUSTOMER BEHAVIOR & BUSINESS PERFORMANCE ANALYSIS")
print("="*80)


# STEP 1: PROBLEM STATEMENT FROM BUSINESS PERSPECTIVE


print("\n" + "="*80)
print("STEP 1: BUSINESS PROBLEM STATEMENT")
print("="*80)

problem_statement = """

BUSINESS PROBLEM:

Over the last few months, revenue growth has slowed down
even though marketing spend has increased.

The business wants clear answers to simple questions:
- Which customers bring the most value?
- Which product categories are actually making money?
- Are we losing customers due to inactivity?
- Where should marketing money be spent for better returns?

This analysis focuses on answering these questions
using customer and transaction data.
"""

print(problem_statement)

# STEP: Accessing Real DataSet
df=pd.read_csv('raw_data_path_enter_here')

df = df.rename(columns={
    'Customer ID': 'customer_id',
    'InvoiceDate': 'transaction_date',
    'Quantity': 'quantity',
    'Price': 'unit_price'
})
print(df.columns)
print('________displaying Descriptive Statical Analysis__')
print(df.describe())

print("printing The information of the data set")
print(df.info())

# STEP 3: DATA CLEANING AND VALIDATION

print("\n" + "="*80)
print("STEP 3: DATA CLEANING AND VALIDATION")
print("="*80)

# Remove rows without customer ID
df = df.dropna(subset=['customer_id'])

# Remove cancelled orders (Invoice starting with 'C')
df = df[~df['Invoice'].astype(str).str.startswith('C')]

# Convert types
df['transaction_date'] = pd.to_datetime(df['transaction_date'])
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
df['unit_price'] = pd.to_numeric(df['unit_price'], errors='coerce')

# Remove invalid rows
df = df[(df['quantity'] > 0) & (df['unit_price'] > 0)]

print("\n--- Initial Data Quality Assessment ---")
print("\nCustomers Dataset:")
print(f"Shape: {df.shape}")
print(f"Missing values:\n{df.isnull().sum()}")
print(f"\nDuplicates: {df.duplicated().sum()}")

df = df.drop_duplicates()
print(f"\nDuplicates: {df.duplicated().sum()}")

print("After removing duplicates:", df.shape)


# EXPLORATORY DATA ANALYSIS
print("\n" + "="*80)
print("EXPLORATORY DATA ANALYSIS")
print("="*80)

print("\nTransaction Revenue Stats:")
df['revenue'] = df['quantity'] * df['unit_price']

print(df['revenue'].describe())

print("\nTop Countries by Revenue:")
country_revenue = df.groupby('Country')['revenue'].agg(['sum','mean','count'])
country_revenue.columns = ['Total Revenue','Avg Order Value','Transaction Count']
print(country_revenue.sort_values('Total Revenue', ascending=False).head(10))

print("\nTop Products by Revenue:")
print(df.groupby('Description')['revenue'].sum()
      .sort_values(ascending=False)
      .head(10))

df['year_month'] = df['transaction_date'].dt.to_period('M')
monthly_revenue = df.groupby('year_month')['revenue'].sum()

print("\nMonthly Revenue Trend (Last 6 months):")
print(monthly_revenue.tail(6))


print(df[['customer_id','transaction_date','revenue']].head())

# CUSTOMER SEGMENTATION

print("\n" + "="*80)
print("STEP 5: CUSTOMER SEGMENTATION (RFM ANALYSIS)")
print("="*80)

from datetime import timedelta

# Reference date for recency calculation
analysis_date = df['transaction_date'].max() + timedelta(days=1)

# Build RFM table
rfm = df.groupby('customer_id').agg({
    'transaction_date': lambda x: (analysis_date - x.max()).days,  # Recency
    'Invoice': 'nunique',                                          # Frequency
    'revenue': 'sum'                                               # Monetary
}).reset_index()

rfm.columns = ['customer_id', 'recency', 'frequency', 'monetary']

# Explain RFM 
# Recency  -> How recently a customer made a purchase
# Frequency-> How often they purchase
# Monetary -> Total revenue generated by the customer

# RFM scoring (1–5 scale)
rfm['r_score'] = pd.qcut(rfm['recency'], 5, labels=[5, 4, 3, 2, 1])
rfm['f_score'] = pd.qcut(rfm['frequency'].rank(method='first'), 5, labels=[1, 2, 3, 4, 5])
rfm['m_score'] = pd.qcut(rfm['monetary'], 5, labels=[1, 2, 3, 4, 5])

# Final RFM score
rfm['rfm_score'] = (
    rfm['r_score'].astype(int) +
    rfm['f_score'].astype(int) +
    rfm['m_score'].astype(int)
)

# Customer segmentation logic
def segment_customer(row):
    if row['rfm_score'] >= 12:
        return 'Champions'
    elif row['rfm_score'] >= 9:
        return 'Loyal Customers'
    elif row['rfm_score'] >= 6:
        return 'Potential Loyalists'
    elif row['rfm_score'] >= 4:
        return 'At Risk'
    else:
        return 'Lost'

rfm['segment'] = rfm.apply(segment_customer, axis=1)

print("\nCustomer Segment Summary:")
segment_summary = rfm.groupby('segment').agg({
    'customer_id': 'count',
    'recency': 'mean',
    'frequency': 'mean',
    'monetary': 'mean'
}).round(2)

segment_summary.columns = [
    'Customer Count',
    'Avg Recency (days)',
    'Avg Purchase Frequency',
    'Avg Revenue'
]

print(segment_summary)

# BUSINESS KPIs AND INSIGHTS

print("\n" + "="*80)
print("STEP 6: KEY PERFORMANCE INDICATORS (KPIs)")
print("="*80)

# -----------------------------
# CORE BUSINESS METRICS
# -----------------------------
total_revenue = df['revenue'].sum()
total_customers = df['customer_id'].nunique()
total_transactions = df['Invoice'].nunique()
avg_order_value = total_revenue / total_transactions

# Customer Lifetime Value (average revenue per customer)
clv = rfm['monetary'].mean()

# Churn calculation (no purchase in last 90 days)
churned_customers = rfm[rfm['recency'] > 90]['customer_id'].count()
churn_rate = (churned_customers / total_customers) * 100

# Repeat purchase rate (more than 1 invoice)
repeat_customers = rfm[rfm['frequency'] > 1]['customer_id'].count()
repeat_rate = (repeat_customers / total_customers) * 100


print("\n--- EXECUTIVE DASHBOARD ---")
print(f"""
╔══════════════════════════════════════════════════════════════╗
║                    KEY BUSINESS METRICS                       ║
╠══════════════════════════════════════════════════════════════╣
║  Total Revenue            £{total_revenue:,.2f}              
║  Total Customers          {total_customers:,}                
║  Total Orders             {total_transactions:,}             
║  Average Order Value      £{avg_order_value:.2f}             
║  Customer Lifetime Value  £{clv:.2f}                         
║  Churn Rate               {churn_rate:.1f}%                  
║  Repeat Purchase Rate     {repeat_rate:.1f}%                 
╚══════════════════════════════════════════════════════════════╝
""")

print("\n--- TOP PRODUCTS BY REVENUE ---")

product_metrics = (
    df.groupby('Description')['revenue']
    .agg(['sum', 'mean', 'count'])
    .round(2)
)

product_metrics.columns = ['Total Revenue', 'Avg Order Value', 'Order Count']
product_metrics['Revenue %'] = (
    product_metrics['Total Revenue'] / total_revenue * 100
).round(2)

print(product_metrics.sort_values('Total Revenue', ascending=False).head(10))


print("\n--- REVENUE BY COUNTRY ---")

country_metrics = (
    df.groupby('Country')
    .agg({
        'revenue': 'sum',
        'customer_id': 'nunique'
    })
    .round(2)
)

country_metrics.columns = ['Total Revenue', 'Unique Customers']
country_metrics['Revenue per Customer'] = (
    country_metrics['Total Revenue'] / country_metrics['Unique Customers']
).round(2)

print(country_metrics.sort_values('Revenue per Customer', ascending=False).head(10))


# Business recomendation

print("\n" + "="*80)
print("STEP 7: STRATEGIC RECOMMENDATIONS FOR STAKEHOLDERS")
print("="*80)

recommendations = f"""
╔══════════════════════════════════════════════════════════════════════════╗
║               ACTIONABLE BUSINESS RECOMMENDATIONS                         ║
╠══════════════════════════════════════════════════════════════════════════╣

FOR MARKETING & CRM TEAMS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. PRIORITIZE CUSTOMER RETENTION
   → Current churn rate is {churn_rate:.1f}%
   → A significant portion of customers have not purchased in the last 90 days
   → Focus on "At Risk" and "Lost" customer segments identified through RFM
   → Action: Launch win-back email campaigns with personalized product offers
   → Expected Impact: Lower churn and increase repeat purchase rate

2. LEVERAGE HIGH-VALUE CUSTOMERS
   → Champions and Loyal Customers contribute a large share of total revenue
   → These customers purchase frequently and spend more per order
   → Action: Introduce VIP benefits such as early access to new products,
            priority support, or small loyalty rewards
   → Expected Impact: Increase Customer Lifetime Value (CLV)

3. SEGMENT-BASED COMMUNICATION
   → Champions: Loyalty rewards and exclusive offers
   → Loyal Customers: Referral and repeat-purchase incentives
   → Potential Loyalists: Limited-time offers to encourage repeat buying
   → At Risk: Personalized “We miss you” messages with top-selling products

FOR PRODUCT & BUSINESS TEAMS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

4. OPTIMIZE PRODUCT FOCUS
   → A small set of products drives a disproportionately high share of revenue
   → Long-tail products generate low revenue and low purchase frequency
   → Action: Promote top-performing products more aggressively
   → Action: Bundle slow-moving products with bestsellers to improve sales

5. PRICING & ORDER VALUE IMPROVEMENT
   → Average Order Value (AOV): £{avg_order_value:.2f}
   → Opportunity exists to increase AOV through bundles and volume discounts
   → Action: Offer “Buy more, save more” pricing on frequently purchased items
   → Expected Impact: Higher revenue without acquiring new customers

FOR FINANCE & OPERATIONS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

6. FOCUS ON CUSTOMER LIFETIME VALUE
   → Current average CLV: £{clv:.2f}
   → Repeat customers generate significantly higher revenue than one-time buyers
   → Action: Track CLV by segment and prioritize retention spending accordingly
   → Expected Impact: Sustainable long-term revenue growth

7. PLAN INVENTORY USING SALES TRENDS
   → Monthly revenue trends indicate seasonality in customer demand
   → Action: Use historical sales patterns to forecast demand
   → Action: Align inventory planning with high-demand months
   → Expected Impact: Reduced stock-outs and lower holding costs

IMMEDIATE 30-DAY ACTION PLAN:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Week 1: Finalize RFM segments and tag customers in CRM
Week 2: Design win-back campaign for At Risk customers
Week 3: Launch loyalty offers for Champions and Loyal Customers
Week 4: Review campaign impact and refine strategy

SUCCESS METRICS TO TRACK:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

• Churn Rate: Reduce below 25% (currently {churn_rate:.1f}%)
• Average Order Value: Increase by 10–15%
• Repeat Purchase Rate: Improve from {repeat_rate:.1f}%
• Customer Lifetime Value: Consistent upward trend
• Revenue from Champions Segment: Increase month-over-month

╚══════════════════════════════════════════════════════════════════════════╝
"""

print(recommendations)

# ============================================================================
# SEGMENT DISTRIBUTION VISUALIZATION
# ============================================================================

plt.figure(figsize=(8, 5))

segment_counts = rfm['segment'].value_counts().sort_values(ascending=False)

sns.barplot(
    x=segment_counts.index,
    y=segment_counts.values
)

plt.title('Customer Segmentation (RFM Analysis)')
plt.xlabel('Customer Segment')
plt.ylabel('Number of Customers')
plt.xticks(rotation=30)

plt.tight_layout()
plt.savefig('Segment_analysis.png', dpi=300)
plt.close()

print(" segment_analysis.png")


# ============================================================================
# SAVE OUTPUTS FOR PRESENTATION
# ============================================================================

print("\n" + "="*80)
print("SAVING ANALYSIS OUTPUTS")
print("="*80)

# 1. Save cleaned transaction-level dataset
df.to_csv('transactions_clean.csv', index=False)
print("✓ Saved: transactions_clean.csv")

# 2. Save RFM customer segments
rfm.to_csv('customer_segments.csv', index=False)
print("✓ Saved: customer_segments.csv")

# 3. Create and save executive KPI summary
summary_metrics = {
    'Metric': [
        'Total Revenue',
        'Total Customers',
        'Total Orders',
        'Average Order Value',
        'Customer Lifetime Value',
        'Churn Rate',
        'Repeat Purchase Rate'
    ],
    'Value': [
        f'£{total_revenue:,.2f}',
        f'{total_customers:,}',
        f'{total_transactions:,}',
        f'£{avg_order_value:.2f}',
        f'£{clv:.2f}',
        f'{churn_rate:.1f}%',
        f'{repeat_rate:.1f}%'
    ]
}

summary_df = pd.DataFrame(summary_metrics)
summary_df.to_csv('executive_summary.csv', index=False)
print("Saved: executive_summary.csv")

print("\n" + "="*80)
print("ANALYSIS COMPLETE - READY FOR PRESENTATION!")
print("="*80)

print("""
Next Steps for Presentation / Interview:
1. Explain how raw data was cleaned and validated
2. Show EDA insights (time trends, countries, top products)
3. Walk through RFM segmentation and customer behavior
4. Highlight key KPIs and what they mean for the business
5. Present actionable recommendations and expected impact
6. Be ready to explain why each step was necessary
""")
